name: CI Security Checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Run SpotBugs (SAST)
        run: gradle spotbugsMain
      - name: Run Snyk
        uses: snyk/actions/setup@master
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}