name: CI Security Checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Run SpotBugs (SAST)
        run: gradle spotbugsMain
      - name: Set up Snyk
        uses: snyk/actions/setup@master
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install snyk-to-html
        run: npm install -g snyk-to-html
      - name: Run Snyk
        run:  |
            snyk test --json > snyk-report.json || true
            snyk-to-html -i snyk-report.json -o snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-html-report
          path: snyk-report.html